# We take names from Wayland which are not camel case.
- ignore:
    name: "Use camelCase"

- warn:
    lhs: "liftIO newEmptyMVar"
    name: "'liftIO' is not needed"
    note: "'newEmptyMVar' from Sayland.Internal.Prelude is already lifted"
    rhs: newEmptyMVar
- warn:
    lhs: "liftIO (putMVar x y)"
    name: "'liftIO' is not needed"
    note: "'putMVar' from Sayland.Internal.Prelude is already lifted"
    rhs: putMVar x y
- warn:
    lhs: "liftIO (newIORef x)"
    name: "'liftIO' is not needed"
    note: "'newIORef' from Sayland.Internal.Prelude is already lifted"
    rhs: newIORef x
- warn:
    lhs: "liftIO (readIORef x)"
    name: "'liftIO' is not needed"
    note: "'readIORef' from Sayland.Internal.Prelude is already lifted"
    rhs: readIORef x
- warn:
    lhs: "liftIO (atomicWriteIORef x y)"
    name: "'liftIO' is not needed"
    note: "'atomicWriteIORef' from Sayland.Internal.Prelude is already lifted"
    rhs: atomicWriteIORef x y
- warn:
    lhs: "liftIO (atomicModifyIORef' x y)"
    name: "'liftIO' is not needed"
    note: "'atomicModifyIORef'' from Sayland.Internal.Prelude is already lifted"
    rhs: atomicModifyIORef' x y
- warn:
    lhs: "liftIO (atomically x)"
    name: "'liftIO' is not needed"
    note: "'atomically' from Sayland.Internal.Prelude is already lifted"
    rhs: atomically x
- warn:
    lhs: "liftIO (throwIO x)"
    name: "'liftIO' is not needed"
    note: "'throwIO' from Sayland.Internal.Prelude is already lifted"
    rhs: throwIO x

- warn:
    lhs: "void (tryTakeMVar x)"
    rhs: tryTakeMVar_ x

- warn:
    lhs: "pure ()"
    name: "Use 'pass'"
    note: "'pass' from Sayland.Internal.Prelude is an alias for 'pure ()'"
    rhs: pass

- arguments:
  # Tests use relude so our custom prelude doesnt apply.
  - "--ignore-glob=test"

  # Our global extensions
  - "-XDuplicateRecordFields"
  - "-XMultiWayIf"
  - "-XNoFieldSelectors"
  - "-XNoImplicitPrelude"
  - "-XOverloadedRecordDot"
  - "-XOverloadedStrings"
  - "-XPartialTypeSignatures"

  # GHC2024 defaults
  - "-XBangPatterns"
  - "-XBinaryLiterals"
  - "-XConstrainedClassMethods"
  - "-XConstraintKinds"
  - "-XDataKinds"
  - "-XDeriveDataTypeable"
  - "-XDeriveFoldable"
  - "-XDeriveFunctor"
  - "-XDeriveGeneric"
  - "-XDeriveLift"
  - "-XDeriveTraversable"
  - "-XDerivingStrategies"
  - "-XDisambiguateRecordFields"
  - "-XDoAndIfThenElse"
  - "-XEmptyCase"
  - "-XEmptyDataDecls"
  - "-XEmptyDataDeriving"
  - "-XExistentialQuantification"
  - "-XExplicitForAll"
  - "-XExplicitNamespaces"
  - "-XFieldSelectors"
  - "-XFlexibleContexts"
  - "-XFlexibleInstances"
  - "-XForeignFunctionInterface"
  - "-XGADTs"
  - "-XGADTSyntax"
  - "-XGeneralisedNewtypeDeriving"
  - "-XHexFloatLiterals"
  - "-XImplicitPrelude"
  - "-XImportQualifiedPost"
  - "-XInstanceSigs"
  - "-XKindSignatures"
  - "-XLambdaCase"
  - "-XMonoLocalBinds"
  - "-XMonomorphismRestriction"
  - "-XMultiParamTypeClasses"
  - "-XNamedFieldPuns"
  - "-XNamedWildCards"
  - "-XNumericUnderscores"
  - "-XPatternGuards"
  - "-XPolyKinds"
  - "-XPostfixOperators"
  - "-XRankNTypes"
  - "-XRelaxedPolyRec"
  - "-XRoleAnnotations"
  - "-XScopedTypeVariables"
  - "-XStandaloneDeriving"
  - "-XStandaloneKindSignatures"
  - "-XStarIsType"
  - "-XTraditionalRecordSyntax"
  - "-XTupleSections"
  - "-XTypeApplications"
  - "-XTypeOperators"
  - "-XTypeSynonymInstances"
  - "-XImplicitStagePersistence"
