= Sayland

Simple Wayland client and server library in Haskell. Allows you to act on events and send requests.
Currently it's a work in progress with many events and requests missing but it's enough to write a simple bar or compositor.

== Usage

don't

== Documentation

View online at https://saygo-png.github.io/sayland/
or build locally using `cabal haddock` and view the html files in a browser/put on a webserver.

== Building

Build with Nix flakes: `nix build`

Build using Cabal: `cabal build`

== Contributing

The project provides a Nix dev shell with Haskell tooling.
You can use it with `nix develop`.

You can format the entire project using `treefmt` or `nix fmt`.
There also is a githook that formats using `treefmt` on each commit.

Run tests using `cabal test`.

To generate docs while hiding certain warnings use `cabal run genHaddocks`.
This program wraps `cabal haddock` and removes bogus warnings related to https://github.com/haskell/haddock/issues/1071.

To inspect generated protocol code run `cabal run unrollTH`.

[Adding a new protocol](./abc/test.md)!
