cabal-version: 3.0
name: sayland
version: 0.0.0
license: GPL-3.0-or-later
license-file: LICENSE.txt
author: saygo-png
maintainer: saygo-png <saygo.mail@proton.me>
category: Graphics
synopsis: Generic, simple Wayland library without C bindings
homepage: https://github.com/saygo-png/sayland
bug-reports: https://github.com/saygo-png/sayland/issues
description:
  Sayland is a WIP, simple Wayland library that doesn't use C bindings.
  It can be used for both clients and compositors.

extra-source-files: xml-protocols/*.xml

common common-options
  build-depends: base >=4.7 && <5
  default-language: GHC2024
  ghc-options:
    -- Use the stub function for unimplemented interfaces
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-missed-specialisations
    -Wno-missing-exported-signatures
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-missing-local-signatures
    -Wno-missing-safe-haskell-mode
    -Wno-safe
    -Wno-unsafe
    -Wno-unticked-promoted-constructors
    -Werror=missing-fields
    -Werror=incomplete-patterns
    -Werror=incomplete-uni-patterns
    -Werror=missing-methods
    -threaded

  default-extensions:
    DuplicateRecordFields
    MultiWayIf
    NoFieldSelectors
    NoImplicitPrelude
    OverloadedRecordDot
    OverloadedStrings
    PartialTypeSignatures

common executable-options
  ghc-options:
    -rtsopts
    -with-rtsopts=-N

library sayland-wire
  import: common-options
  visibility: public
  -- Boot libraries.
  build-depends:
    binary,
    bytestring,
    directory,
    filepath,
    mtl,
    template-haskell,
    text,
    unix,

  -- Non-boot libraries.
  build-depends:
    network,
    shared-memory,

  hs-source-dirs: lib-wire
  -- cabal-gild: discover lib-wire
  exposed-modules:
    Sayland.Internal.Connection
    Sayland.Internal.Wire
    Sayland.Wire

library
  import: common-options
  -- Boot libraries.
  build-depends:
    binary,
    bytestring,
    containers,
    directory,
    filepath,
    mtl,
    stm,
    template-haskell,
    text,
    unix,

  -- Non-boot libraries.
  build-depends:
    ansi-terminal,
    network,
    sayland-wire,
    shared-memory,
    xml,

  hs-source-dirs: lib
  -- cabal-gild: discover lib
  exposed-modules:
    Sayland
    Sayland.Connection
    Sayland.Core
    Sayland.Internal.Codegen
    Sayland.Internal.Core
    Sayland.Internal.Object
    Sayland.Internal.Prelude
    Sayland.Internal.Protocols.DmaBuf
    Sayland.Internal.Protocols.Fifo
    Sayland.Internal.Protocols.Wayland
    Sayland.Internal.Protocols.WlrLayerShell
    Sayland.Internal.Protocols.XdgShell
    Sayland.Internal.Trace
    Sayland.Object
    Sayland.Protocols.DmaBuf
    Sayland.Protocols.Fifo
    Sayland.Protocols.Wayland
    Sayland.Protocols.WlrLayerShell
    Sayland.Protocols.XdgShell

executable genHaddocks
  import: common-options, executable-options
  hs-source-dirs: debug
  main-is: GenHaddocks.hs
  build-depends:
    base,
    process,
    template-haskell,
    text,

executable unrollTH
  import: common-options, executable-options
  hs-source-dirs: debug
  main-is: UnrollTH.hs
  build-depends:
    base,
    process,
    sayland,
    template-haskell,

test-suite sayland-tests
  import: common-options, executable-options
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  -- cabal-gild: discover test --exclude=test/Main.hs
  other-modules:
    Both.Protocol.Codegen
    Both.Wire
    Client.BasicWindow
    Client.WallpaperDaemon
    Server.BasicCompositor
    TestUtils

  build-depends:
    QuickCheck,
    base,
    binary,
    bytestring,
    containers,
    directory,
    network,
    random,
    relude,
    sayland,
    sayland-wire,
    stm,
    tasty,
    tasty-hunit,
    tasty-quickcheck,
    template-haskell,
    unix,
