-- | Description : Core of the library that most other modules depend on.
module Sayland.Core (
  Wayland,
  Perspective (..),
  GlobalName (..),
  Object (..),
  TObjectID,
  Outgoing,
  Incoming,
  Global (..),
  ClientEnvironment (..),
  ServerEnvironment (..),
  KnownPerspective (..),
  EventHandler (..),
  Interface (..),
  SomeObject (..),
  Message (..),
  MessageError (..),
  runGetMessage,
  WaylandEnv (..),
  InterfaceEntry (..),
  ProtocolTable,
  Strictness (..),
  Culprit (..),
  Severity (..),
  getStrictness,
  protocolViolation,
) where

import Sayland.Internal.Core
